path:
  data: /data/data
  logs: /data/log
  work: /data/work
network:
  host: _non_loopback_
cluster:
  name: ${ES_CLUSTER_NAME}
cloud:
  aws:
  # these credentials are restricted to only DescribeInstances
    access_key: ${ES_AWS_ACCESS_KEY}
    secret_key: ${ES_AWS_SECRET_KEY}
    region: ${ES_AWS_REGION}
discovery:
  type: ec2
  ec2:
    groups: ${ES_CLUSTER_NAME}
